import Providers from "@/components/Providers";
import "./globals.css";
import Appbar from "@/components/Appbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* <Appbar /> */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
